# Default values for desktop-tensorflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

datasets_list: ""

requests: 
  gpu: false
  cpu: "1"
  memory: "4Gi"

configmaps:
  chaimeleon: "chaimeleon"

