apiVersion: chaimeleon.eu/v1
kind: DatasetConsumer
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.name }}"
  annotations: 
    "helm.sh/hook": "pre-install"
spec:  
    datasetIDs: 
        {{- toYaml .Values.datasets_list | nindent 6 }}
    consumer: 
        apiVersion: apps/v1
        kind: Deployment
        metadata:
            name: "DatasetConsumer-{{ .Chart.Name }}-{{ .Values.name }}"
            labels:
                {{- include "desktop-tensorflow.labels" . | nindent 16 }}    
        spec:
            replicas: 1
            selector:
                matchLabels:
                    app: "{{ .Chart.Name }}-{{ .Values.name }}"
            template:
                metadata:
                    labels:
                        app: "{{ .Chart.Name }}-{{ .Values.name }}"
                spec:
                    volumes:
                        - name: datalake
                          cephfs:
                            path: "{{- include "chaimeleon.datalake.path" . -}}" 
                            user: "{{- include "chaimeleon.ceph.user" . -}}" 
                            monitors:
                                - "{{- include "chaimeleon.ceph.monitor" . -}}"  
                            secretRef:
                                name: "ceph-auth"
                            readOnly: true
                        - name: home
                          cephfs:
                            path: "{{- include "chaimeleon.persistent_home.path" . -}}" 
                            user: "{{- include "chaimeleon.ceph.user" . -}}" 
                            monitors:
                                - "{{- include "chaimeleon.ceph.monitor" . -}}"  
                            secretRef:
                                name: "ceph-auth"
                            readOnly: true
                        {{- range $datasetID := .Values.datasets_list }}
                        - name: "{{ $datasetID -}}"
                          cephfs:
                            path: "{{- include "chaimeleon.datasets.path" $ -}}/{{- $datasetID -}}"
                            monitors:
                                - "{{- include "chaimeleon.ceph.monitor" $ -}}"  
                            user: "{{- include "chaimeleon.ceph.user" $ -}}" 
                            secretRef:
                                name: "ceph-auth"
                            readOnly: true 
                        {{- end }}
                    securityContext:
                        #runAsUser: {{- include "chaimeleon.user.uid" . }}
                        #runAsGroup: {{- include "chaimeleon.group.gid" . }}
                        supplementalGroups: [ {{- include "chaimeleon.ceph.gid" . }} ] 
                    containers:
                        - name: {{ .Chart.Name }}
                          image: "{{ .Values.docker_image }}"
                          imagePullPolicy: Always
                          volumeMounts:
                            - mountPath: "{{- include "chaimeleon.datalake.mount_point" . -}}"
                              name: datalake
                            - mountPath: "{{- include "chaimeleon.persistent_home.mount_point" . -}}"
                              name: home
                            {{- range $datasetID := .Values.datasets_list }}
                            - mountPath: "{{- include "chaimeleon.datasets.mount_point" $ -}}"
                              name: "{{ $datasetID -}}"
                             {{- end }}
                          ports:
                            - containerPort: 22
                              name: sshd
                            - containerPort: 5900
                              name: vnc-gui        
                          env:
                            - name: USER
                              value: "{{- include "chaimeleon.user.name" . }}"
                            - name: PASSWORD
                              value: "{{ .Values.user.password }}"
                            - name: SSH_ENABLE_PASSWORD_AUTH
                              value: "true"
                            - name: GATEWAY_PORTS
                              value: "true"
                            - name: TCP_FORWARDING
                              value: "true"