apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "desktop-tensorflow.fullname" . }}"
  annotations: 
    {{- include "desktop-tensorflow.annotations" . | nindent 4 }}  
  labels:
    {{- include "desktop-tensorflow.labels" . | nindent 4 }}    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "desktop-tensorflow.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "desktop-tensorflow.fullname" . }}"
    spec:
      volumes:
        - name: datalake
          cephfs:
            path: "{{- include "chaimeleon.datalake.path" . -}}" 
            user: "{{- include "chaimeleon.ceph.user" . -}}" 
            monitors:
                - "{{- include "chaimeleon.ceph.monitor" . -}}"  
            secretRef:
                name: "ceph-auth"
            readOnly: true
        - name: home
          cephfs:
            path: "{{- include "chaimeleon.persistent_home.path" . -}}" 
            user: "{{- include "chaimeleon.ceph.user" . -}}" 
            monitors:
                - "{{- include "chaimeleon.ceph.monitor" . -}}"  
            secretRef:
                name: "ceph-auth"
            readOnly: true
        
        {{- range $datasetID := splitList "," .Values.datasets_list }}
        - name: "{{ $datasetID -}}"
          cephfs:
            path: "{{- include "chaimeleon.datasets.path" $ -}}/{{- $datasetID -}}"
            monitors:
                - "{{- include "chaimeleon.ceph.monitor" $ -}}"  
            user: "{{- include "chaimeleon.ceph.user" $ -}}" 
            secretRef:
                name: "ceph-auth"
            readOnly: true 
        {{- end }}

      securityContext:
        runAsUser: {{ include "chaimeleon.user.uid" . }}
        runAsGroup: {{ include "chaimeleon.group.gid" . }}
        supplementalGroups: [ {{ include "chaimeleon.ceph.gid" . }} ] 

      containers:
      - name: {{ .Chart.Name }}
        image: "chaimeleon-eu.i3m.upv.es:10443/chaimeleon-library/ubuntu_python_tensorflow_gpu_desktop_vnc_sshd:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
{{- if .Values.requestGPU }}
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
{{- end }}
        volumeMounts:
          - mountPath: "{{- include "chaimeleon.datalake.mount_point" . -}}"
            name: datalake
          - mountPath: "{{- include "chaimeleon.persistent_home.mount_point" . -}}"
            name: home
            
          {{- range $datasetID := splitList "," .Values.datasets_list }}
          - mountPath: "{{- include "chaimeleon.datasets.mount_point" $ -}}/{{- $datasetID -}}"
            name: "{{ $datasetID -}}"
            {{- end }}

        ports:
          - containerPort: 2222
            name: sshd
          - containerPort: 5900
            name: vnc-gui
        env:
          # password for "chaimeleon" (OS and SSH) user
          - name: PASSWORD
            value: "{{ .Values.user.password }}"

          # password for VNC access (empty username)
          - name: VNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "desktop-tensorflow.fullname" . }}"
                key: vnc_password

{{- if .Values.guacamoleConnectionCreation.guacamoleUserSecretName }}
          # Parameters required for automatically create the connection in Guacamole for this container
          - name: GUACAMOLE_URL
            value: "{{ .Values.guacamoleConnectionCreation.guacamoleUrl }}"
          - name: GUACD_HOST
            value: "{{ .Values.guacamoleConnectionCreation.guacdHost }}"
          - name: GUACAMOLE_USER
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.guacamoleConnectionCreation.guacamoleUserSecretName }}"
                key: user
          - name: GUACAMOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.guacamoleConnectionCreation.guacamoleUserSecretName }}"
                key: password
          - name: GUACAMOLE_CONNECTION_NAME
            value: "{{- include "desktop-tensorflow.connectionName" . -}}"
{{- end }}
          - name: SSH_ENABLE_PASSWORD_AUTH
            value: "true"
          - name: GATEWAY_PORTS
            value: "true"
          - name: TCP_FORWARDING
            value: "true"

