apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.name }}"
  annotations: 
    "chaimeleon.eu/datasetsIDs": "{{ join ", " .Values.datasets_list }}"
    "chaimeleon.eu/toolName": "{{ .Chart.Name }}"
    "chaimeleon.eu/toolVersion": "{{ .Chart.Version | quote }}"
  labels:
    {{- include "desktop-tensorflow.labels" . | nindent 4 }}    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-{{ .Values.name }}"
    spec:
      volumes:
        - name: datalake
          cephfs:
            path: "{{- include "chaimeleon.datalake.path" . -}}" 
            user: "{{- include "chaimeleon.ceph.user" . -}}" 
            monitors:
                - "{{- include "chaimeleon.ceph.monitor" . -}}"  
            secretRef:
                name: "ceph-auth"
            readOnly: true
        - name: home
          cephfs:
            path: "{{- include "chaimeleon.persistent_home.path" . -}}" 
            user: "{{- include "chaimeleon.ceph.user" . -}}" 
            monitors:
                - "{{- include "chaimeleon.ceph.monitor" . -}}"  
            secretRef:
                name: "ceph-auth"
            readOnly: true
        {{- range $datasetID := .Values.datasets_list }}
        - name: "{{ $datasetID -}}"
          cephfs:
            path: "{{- include "chaimeleon.datasets.path" $ -}}/{{- $datasetID -}}"
            monitors:
                - "{{- include "chaimeleon.ceph.monitor" $ -}}"  
            user: "{{- include "chaimeleon.ceph.user" $ -}}" 
            secretRef:
                name: "ceph-auth"
            readOnly: true 
        {{- end }}

      securityContext:
          #runAsUser: {{ .Values.user.uid }}
          #runAsGroup: {{ .Values.user.gid }}
          supplementalGroups: [ {{- include "chaimeleon.ceph.gid" . }} ] 

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.docker_image }}"
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "{{- include "chaimeleon.datalake.mount_point" . -}}"
            name: datalake
          - mountPath: "{{- include "chaimeleon.persistent_home.mount_point" . -}}"
            name: home
          {{- range $datasetID := .Values.datasets_list }}
          - mountPath: "{{- include "chaimeleon.datasets.mount_point" $ -}}/{{- $datasetID -}}"
            name: "{{ $datasetID -}}"
            {{- end }}
        ports:
          - containerPort: 22
            name: sshd
          - containerPort: 5900
            name: vnc-gui        
        env:
          - name: USER
            value: "{{- include "chaimeleon.user.name" . }}"
          - name: PASSWORD
            value: "{{ .Values.user.password }}"
          - name: SSH_ENABLE_PASSWORD_AUTH
            value: "true"
          - name: GATEWAY_PORTS
            value: "true"
          - name: TCP_FORWARDING
            value: "true"

