apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.name }}"
  #{{ include "desktop-tensorflow.fullname" . }}
  labels:
    {{- include "desktop-tensorflow.labels" . | nindent 4 }}    
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  securityContext:
    runAsUser: {{ .Values.user.uid }}
    runAsGroup: {{ .Values.user.gid }}
    supplementalGroups:
    {{- toYaml .Values.dataset.gid_list  | nindent 6 }}
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      image: "primage/interactive:{{ .Chart.AppVersion }}"
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: "{{ .Values.datasets.rootfs_mount_dir}}"
        name: rootfs
      - mountPath: "{{ .Values.dataset.mount_point}}"
        name: dataset
      ports:
      - containerPort: 22
        name: sshd
      - containerPort: 5900
        name: vnc
      env:
         # Ubuntu user
        - name: USER
          value: "{{ .Values.user.username }}"
        - name: PASSWORD
          value: "{{ .Values.user.password }}"
        - name: SSH_ENABLE_PASSWORD_AUTH
          value: "true"
        - name: GATEWAY_PORTS
          value: "true"
        - name: TCP_FORWARDING
          value: "true"
        # Parameters required for automatically create the connection in Guacamole for this container
        # Comment this bloc if you don't want to create the connection
        # - name: GUACAMOLE_HOST
        #   value: "{{ .Values.guacamoleConnectionCreation.host }}"
        # - name: GUACAMOLE_PORT
        #   value: "{{ .Values.guacamoleConnectionCreation.port }}"
        # - name: GUACAMOLE_PATH
        #   value: "{{ .Values.guacamoleConnectionCreation.path }}"
        # - name: GUACD_HOST
        #   value: "{{ .Values.guacamoleConnectionCreation.guacdHost }}"
        # - name: GUACAMOLE_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ include "desktop-tensorflow.fullname" . }}
        #       key: guacamole-user
        # - name: GUACAMOLE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ include "desktop-tensorflow.fullname" . }}
        #       key: guacamole-password
  volumes:
    - name: rootfs
      cephfs:
        path: "{{ .Values.datasets.rootfs_dir }}"
        monitors:
        {{- toYaml .Values.datasets.monitor_list | nindent 8 }}
        user: "{{ .Values.ceph.user }}"
        secretRef:
          name: "{{ .Values.name }}-secret"
        readOnly: true
    - name: dataset
      cephfs:
        path: "{{ .Values.datasets.datasets_dir }}/{{ .Values.dataset.id }}"
        monitors:
        {{- toYaml .Values.datasets.monitor_list | nindent 8 }}
        user: "{{ .Values.ceph.user }}"
        secretRef:
          name: "{{ .Values.name }}-secret"
        readOnly: true  
    