apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "desktop-tensorflow.fullname" . }}"
type: Opaque
stringData:
  # Ceph auth key
  key: "{{ .Values.ceph.key }}"
  vnc_password: "{{ include "desktop-tensorflow.randomString" . }}"
