apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "desktop-tensorflow.fullname" . }}"
type: Opaque
stringData:
  vnc_password: "{{ include "desktop-tensorflow.randomString" . }}"
  container-user: "{{- include "chaimeleon.user.name" $ }}"
  container-password: "{{ .Values.user.password }}"