apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.name }}"
type: Opaque
stringData:  
  # Your credentials to access Guacamole (required to create connections automatically for containers)
  guacamole-user: "{{ .Values.guacamoleConnectionCreation.guacamoleUser }}"
  guacamole-password: "{{ .Values.guacamoleConnectionCreation.guacamolePassword }}"
