apiVersion: v1
kind: Service
metadata:
    name: "{{ .Chart.Name }}-{{ .Values.name }}"
spec:
    selector:
        app: "{{ .Chart.Name }}-{{ .Values.name }}"
    type: ClusterIP
    ports:
      - name: sshd
        port: 22
        targetPort: 22
      - name: vnc-gui
        port: 5900
        targetPort: 5900
