apiVersion: v1
kind: Service
metadata:
    name: "{{ include "desktop-tensorflow.fullname" . }}"
spec:
    selector:
        app: "{{ include "desktop-tensorflow.fullname" . }}"
    type: ClusterIP
    ports:
    - port: 2222
      targetPort: 2222
      name: sshd
    - port: 5900
      targetPort: 5900
      name: vnc-gui
