apiVersion: v1
kind: Service
metadata:
    name: "{{ include "desktop-tensorflow.fullname" . }}"
spec:
    selector:
        app: "{{ include "desktop-tensorflow.fullname" . }}"
    type: ClusterIP
    ports:
    - name: sshd-svc
      port: 2222
      targetPort: sshd
    - name: vnc-gui-svc
      port: 5900
      targetPort: vnc-gui